repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
    - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
    - id: mypy
      additional_dependencies:
        - 'types-PyYAML'
